spring.application.name=agenda-telefonica

spring.datasource.url=jdbc:postgresql://localhost:5432/agenda_telefonica
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

server.port=8080
